spring:
  drools:
    # 指定规则文件文件夹，会自动扫描该目录下所有规则文件，决策表，以及CSV文件
    path: /home/rules/
    # 也可以指定全局的mode,选择stream或者cloud
    mode: stream
    # 指定规则文件自动更新的周期，单位秒，默认30秒扫描一次
    update: 5
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/portal_song?useSSL=false
#      url:  jdbc:mysql://localhost:3306/portal@song?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
#      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
localpath:
  template: D:\test\daily\template
